// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BDO.Report
{
    [Serializable]
    [DataContract(Name = "RptBasicInfo", Namespace = "http://www.KAF.com/types")]
   
    public partial class RptBasicInfo
    {
        public long BasicInfoId { get; set; }
        public string CivilId { get; set; }
        public string PassportNo { get; set; }
        public string FullName { get; set; }
        public DateTime Dob { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string Name5 { get; set; }
        public long? Gender { get; set; }
        public string Mob1 { get; set; }
        public string Mob2 { get; set; }
        public string Mob3 { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string Email { get; set; }
        public long? PreAddCountryId { get; set; }
        public long? PreAddGovernId { get; set; }
        public string PreAddGovernarate { get; set; }
        public long? PreAddCityId { get; set; }
        public string PreAddCity { get; set; }
        public string PreAddStreet { get; set; }
        public string PreAddBlock { get; set; }
        public string PreAddHousingNo { get; set; }
        public string PreAddHousingFlatNo { get; set; }
        public string PreAddress { get; set; }
        public string PrePaci { get; set; }
        [DataMember]
        public string Nationality { get; set; }
        public string ClassName { get; set; }
        public string BloodGroupName { get; set; }
        public string MaritalStatus { get; set; }
        public long BirthCountryId { get; set; }
        public string BirthCountry { get; set; }
        public string ReligionName { get; set; }
        public string PerPaci { get; set; }
        public string PresentCountry { get; set; }



        //heee
    }
}