// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BDO.Report
{
    public partial class RptRegistrationInfo
    {
        public long RegistrationId { get; set; }
        public long BasicInfoId { get; set; }
        public DateTime? ApplicationDate { get; set; }
        public string AppliedFromIp { get; set; }
        public bool? IsActive { get; set; }
        public long? Idtype { get; set; }
        public DateTime? IdissueDate { get; set; }
        public DateTime? IdexpiryDate { get; set; }
        public long? BatchCandidateTypeMapId { get; set; }
        public long? BatchNo { get; set; }
        public long? CandidateTypeId { get; set; }
        public long? BatchCandProfessionMapId { get; set; }
        public long? ProfessionId { get; set; }
        public long? BatchUnitListId { get; set; }
        public string ProfessionName { get; set; }
        [DataMember]
        public string CandidateTypeName { get; set; }
        
        [DataMember]
        public string BatchDetails { get; set; }
        


    }

}